### ISSUE TITLE
mate-keyboard-properties crashes

### ISSUE THREAD

**Issue by xmirya** [jlmess77/mate-ports#1]
Got FreeBSD-9.2-RC3/amd64 with NEW_XORG stack, opening mate-keyboard-properties (i've got 3 layouts) and going to Layout tab -> Parameters button makes it coredump. The console dumps the following line 9 times:

```
(mate-keyboard-properties:2391): GLib-CRITICAL **: g_convert: assertion `str != NULL' failed
```

, then the process dumps the core. The core backtrace follows:

```
#0  0x000000080b8cfa8c in strcmp () from /lib/libc.so.7
#1  0x0000000809dd769d in g_utf8_collate () from /usr/local/lib/libglib-2.0.so.0
#2  0x0000000809dc5dc2 in g_slist_sort_real () from /usr/local/lib/libglib-2.0.so.0
#3  0x0000000809dc5d73 in g_slist_sort_real () from /usr/local/lib/libglib-2.0.so.0
#4  0x000000000040bdb2 in xkb_options_popup_dialog ()
#5  0x000000080814dab2 in xkl_config_registry_foreach_option_group () from /usr/local/lib/libxklavier.so.12
#6  0x000000000040b98d in xkb_options_load_options ()
#7  0x000000000040badd in xkb_options_popup_dialog ()
#8  0x000000080991906d in _g_closure_invoke_va () from /usr/local/lib/libgobject-2.0.so.0
#9  0x000000080992f9db in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#10 0x0000000809930b13 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#11 0x0000000803a90309 in gtk_button_set_alignment () from /usr/local/lib/libgtk-x11-2.0.so.0
#12 0x000000080991906d in _g_closure_invoke_va () from /usr/local/lib/libgobject-2.0.so.0
#13 0x000000080992f9db in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#14 0x0000000809930b13 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#15 0x0000000803a8e739 in gtk_button_released () from /usr/local/lib/libgtk-x11-2.0.so.0
#16 0x0000000803b39b7f in gtk_marshal_BOOLEAN__VOID () from /usr/local/lib/libgtk-x11-2.0.so.0
#17 0x00000008099192f3 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.0
#18 0x000000080992e34a in signal_emit_unlocked_R () from /usr/local/lib/libgobject-2.0.so.0
#19 0x000000080992ff7a in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#20 0x0000000809930b13 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#21 0x0000000803c49e85 in gtk_widget_style_attach () from /usr/local/lib/libgtk-x11-2.0.so.0
#22 0x0000000803b327d9 in gtk_propagate_event () from /usr/local/lib/libgtk-x11-2.0.so.0
#23 0x0000000803b33908 in gtk_main_do_event () from /usr/local/lib/libgtk-x11-2.0.so.0
#24 0x00000008044966cc in gdk_add_client_message_filter () from /usr/local/lib/libgdk-x11-2.0.so.0
#25 0x0000000809da9eaa in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#26 0x0000000809dabc98 in g_main_context_iterate () from /usr/local/lib/libglib-2.0.so.0
#27 0x0000000809dacdc9 in g_main_loop_run () from /usr/local/lib/libglib-2.0.so.0
#28 0x0000000803b33ca3 in gtk_main () from /usr/local/lib/libgtk-x11-2.0.so.0
#29 0x00000000004076da in main ()
```

Unable to find anything in the mate bugtracker, so guess it's FreeBSD port-specific.

Note: devel/glib20 is built WITH_COLLATION_FIX

**Comment by kwm81** [comment]
I don't have parameters button, do you mean options?

**Comment by xmirya** [comment]
1) I've got LANG set to uk_UA.KOI8-U , and yes, it's named "Options" in C locale, sorry for confusion
2) Checking the above, i've just discovered it doesn't crash when run with C locale, e.g.

```
LANG=C mate-keyboard-options
```

, while crashes with the above backtrace when run as

```
LANG=uk_UA.KOI8-U mate-keyboard-options
```

**Comment by kwm81** [comment]
I'm not getting any tracktion on this, can you report this upstream?

**Comment by ericbsd** [comment]
I have Xorg compile NEW_XORG and mate-keyboard-properties work well.

**Comment by ghost** [comment]
I have same issue:

LC_ALL=en_EN.UTF-8 mate-keyboard-properties - works fine
LC_ALL=**_**.UTF-8 mate-keyboard-properties - segfault when click to "Options button" on "Layouts" tab.

This error is same with gnome-keyboard-properties. Idk why developers still didnt fix this bug since 2011.

NEW_XORG is still unstable, if this is xorg issue (i think mate developers can fix this) - I will wait freebsd 11
